import de.itemis.mps.gradle.*

import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle

//will pull the groovy classes/types from nexus to the classpath
buildscript {
    repositories {
        maven { url = 'https://artifacts.itemis.cloud/repository/maven-mps/' }
        mavenCentral()
    }
    dependencies {
        classpath 'de.itemis.mps:mps-gradle-plugin:1.30.+'
    }
}

plugins {
    id 'base'
    id 'maven-publish'
    id "com.github.breadmoirai.github-release" version "2.5.2"
}

def incrementalBuild = !project.hasProperty("disableIncrementalBuild")
def artifactsDir = layout.buildDirectory.dir('artifacts').get().asFile


configurations {
    mps
    languageLibs
    junitAnt
}

dependencies {
    mps "com.jetbrains:mps:2022.3.+"
    languageLibs "com.mbeddr:mbeddr:2022.3.+"
    junitAnt 'org.apache.ant:ant-junit:1.10.17'
}

repositories {
        maven {
            url = "https://artifacts.itemis.cloud/repository/maven-mps/"
        }

    mavenCentral()
}

task resolveMps(type: Copy) {
    dependsOn configurations.mps
    from {
        configurations.mps.resolve().collect { zipTree(it) }
    }
    into layout.buildDirectory.dir("mps")
}

task resolveAllLanguageLibs(type: Copy) {
    from {
        configurations.languageLibs.resolve().collect { zipTree(it) }
    }
    into layout.buildDirectory.dir("dependencies")
}

def dflatVersion = project.findProperty("dflatVersion") ?: '0.1'

// Default arguments for ant scripts
def defaultScriptArgs = [
        'mps.home'                          : resolveMps.destinationDir,
        'dflat.home'                        : projectDir,
        'build.dir'                         : layout.buildDirectory.get().asFile,
        'mps.generator.skipUnmodifiedModels': incrementalBuild,
        'version'                           : dflatVersion,
        'dflat.version'                     : dflatVersion,
]
def defaultScriptClasspath = project.configurations.junitAnt.asFileTree

// enables https://github.com/mbeddr/mps-gradle-plugin#providing-global-defaults
ext["itemis.mps.gradle.ant.defaultScriptArgs"] = defaultScriptArgs.collect { "-D$it.key=$it.value".toString() }
ext["itemis.mps.gradle.ant.defaultScriptClasspath"] = defaultScriptClasspath


task buildAllScripts(type: BuildLanguages, dependsOn: [resolveMps, resolveAllLanguageLibs]) {
    script = "scripts/allScripts.xml"
}

task buildLanguages(type: BuildLanguages, dependsOn: buildAllScripts) {
    script = "${layout.buildDirectory.get().asFile}/languageBuild.xml"
}

task packageLanguages(type: Zip, dependsOn: buildLanguages) {
    archiveBaseName = 'com.dslfoundry.dflat'
    from artifactsDir
    include 'com.dslfoundry.dflat/**'
}

task setup {
    dependsOn resolveAllLanguageLibs
    description = 'Set up MPS project libraries. Libraries are read in from projectlibraries.properties file.'
}


def releaseArtifacts = ["${artifactsDir}/com.dslfoundry.dflat/com.dslfoundry.dflat-${dflatVersion}.zip"]

githubRelease {
    owner = 'DSLFoundry'
    repo = 'mps-dflat'
    token =  providers.environmentVariable("GITHUB_TOKEN").getOrElse("empty")
    tagName =  "v-$dflatVersion"
    targetCommitish = providers.environmentVariable("CI_COMMIT_SHA").getOrElse("master")
    releaseName =  "MPS C# Implementation Extensions v$dflatVersion"
    releaseAssets = releaseArtifacts
    // body = ReleaseNotes.getReleaseNotes(file("RELEASE_NOTES.md"))
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/DSLFoundry/mps-dflat")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
    
    publications {
        gpr(MavenPublication) {
            groupId = 'com.dslfoundry.dflat'
            artifactId = 'dflat'
            version = "$dflatVersion"
            
            artifacts = releaseArtifacts
            pom {
                name = "MPS C# Implementation"
                url = "https://github.com/DSLFoundry/`mps-dflat"
            }
        }
    }
}

build.dependsOn buildLanguages
tasks.named("githubRelease") { dependsOn(tasks.named("build"))}

defaultTasks 'buildLanguages'

publish.dependsOn build
